### ISSUE TITLE
Implement visual design for FOIA request form (front stage)

### ISSUE THREAD

**Issue by vz3** [18F/beta.foia.gov#101]
As a requester, in order to submit a request to a specific agency, I need a form to fill out my request with the latest visual design.

This should be based on the latest style tile.

Sketch file (GSA only):
https://drive.google.com/open?id=0B5ZkkkN_EN7iSm9VcFZ5aEZXN2s

![option 2 - mockup copy 3](https://user-images.githubusercontent.com/582918/29943439-5448fd04-8e4e-11e7-839b-1f6009ff5b73.png)
![option 2 - mockup copy](https://user-images.githubusercontent.com/582918/29943438-5448863a-8e4e-11e7-8918-174c65178e1a.png)

## Acceptance criteria

- [ ] Front stage request form includes the same scss sources as the agency info updater (back stage)
- [ ] Includes latest visual design

**Comment by adborden** [comment]
For decentralized agencies, how do we want to distinguish between agency and agency component? For example, if I was looking at the form for OIP, would I see "Department of Justice" anywhere?

**Comment by AvivaOskow** [comment]
Most recent
![foia_style-tile_r3_form_9 12 17](https://user-images.githubusercontent.com/21244661/30389372-a1e56bd8-9880-11e7-9cc0-e609e2caa02f.jpg)

**Comment by adborden** [comment]
@hbillings  and @AvivaOskow will discuss which parts are ready to be implemented and adjust the issue appropriately.

**Comment by AvivaOskow** [comment]
![form - agency-info_tab](https://user-images.githubusercontent.com/21244661/30924894-b3d64902-a375-11e7-999c-bc18e3445d24.jpg)
![form - directions_tab](https://user-images.githubusercontent.com/21244661/30924895-b3e3f7fa-a375-11e7-96a6-77370cbee4ab.jpg)
