### ISSUE TITLE
Port agency finder from open.foia.gov

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#108]
As a requester, in order to find the correct agency component to submit my request to, I need a UI that interactively shows me related agency components.

We've identified that the UI from open.foia.gov is a good starting point. I think the javascript is [here](https://github.com/18F/2015-foia-hub/blob/master/foia_hub/static/js/search.js).

## Acceptance criteria

- [x] An input field allows the requester to type the agency or agency component.
- [x] The input field has typeahead.
- [x] Selecting an agency component shows you the agency component's request form, or takes you to a new page with the agency component's request form.
- [x] Data for typeahead is powered by an agency component listing API
- [x] Data fetching uses pagination

**Comment by adborden** [comment]
There's potential for this type of UI widget to be used in other applications, so we might want it to be re-usable. Let's not pre-optimize for this just yet, but something to keep in mind.

**Comment by adborden** [comment]
@vz3 @RyanSibley looking at https://open.foia.gov, and wondering how you want to handle decentralized agencies. Taking FBI as an example, I think it's important to capture the abbreviation in addition to the agency component name. But, I'm wondering if typing DOJ should also match FBI.

The other example is APHIS at the USDA. In that case, USDA should definitely match, because USDA is much more well known than APHIS. People probably want to type USDA to browse the lesser known components.

So there's a question of how to present it. We were using something like this in our [prototype](https://foia-form-wizard.app.cloud.gov/request/):
```
Animal & Plant Health Inspection Service (USDA)
```
This includes the component name and the agency abbreviation, but not the component abbreviation. Should it?

**Comment by adborden** [comment]
Oops, the prototype actually included the agency name:
```
Animal & Plant Health Inspection Service, Department of Agriculture (USDA)
```

**Comment by RyanSibley** [comment]
What happens if people only type APHIS? If "Animal & Plant Health
Inspection Service, Department of Agriculture (USDA)" appears great, but if
not, then APHIS should be included in the DB. Let me know if I'm not making
sense.

**Comment by adborden** [comment]
+ @AvivaOskow

**Comment by adborden** [comment]
@RyanSibley yeah, that's part of my question. Based on conversation today it sounds like the typeahead should match on abbreviations, so typing "APHIS" or "USDA" would both match "Animal & Plant Health Inspection Service".

It's still a bit early in the design, so I'm going to try not to focus on the behaviors too much until we firm those up. However it sounds like we want to make a distinction between tier 1 selections and tier 2  (so you could select "Department of Agriculture" in addition to "Animal & Plant Health Inspection Service", although the behavior would be different.

**Comment by adborden** [comment]
The pagination limit is enforced on the back end, so we're going to have to implement paging of the API requests.
