### ISSUE TITLE
Add Glossary widget to front stage

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#115]
As a requester, in order to access quick, contextual explanation for complex FOIA terminology, I need a glossary that can be embedded on any page's content.

https://github.com/18F/glossary

## Acceptance criteria

- [x] Initialize the Glossary on the Portal pages
- [x] Glossary contains the terms that we've defined so far
- [x] Terms defined in JSON in a single file
- [x] README contains a link to the JSON terms so content folks can quickly locate it.

**Comment by adborden** [comment]
@RyanSibley did you have a new doc with some terms that we should start with or should we use the [glossary from discovery](https://github.com/18F/foia-recommendations/blob/master/Glossary.md)?

**Comment by RyanSibley** [comment]
Let's use the doc from discovery. thank you for asking, though.

**Comment by adborden** [comment]
The desire is to have all the legacy pages include the glossary as well. That could be difficult because working with the legacy javascript has been challenging. If the lift isn't too high, let's aim for getting this on all the jekyll pages. Otherwise, it will only be on the Portal pages.

**Comment by RyanSibley** [comment]
I wasn't envisioning this on legacy pages, because that would require linking terms on those pages to make it appear. Unless the legacy pages will also have the new footer? @adborden
