### ISSUE TITLE
Travis CI Setup

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#117]
As a developer, in order to have tests run in a continuous and automated fashion, I need to setup Travis CI for the usdoj foia repo.

## Acceptance criteria

- [ ] Tests are executed when pull requests are opened
- [ ] Tests are executed when pull requests are updated
- [ ] Tests are executed when a branch is merged into the `develop` branch
- [ ] A build artifact is deployed to the `stage` environment on merge into the `develop` branch and tests run successfully

**Comment by malikkotob** [comment]
No longer needed.

**Comment by adborden** [comment]
We no longer need a CI environment?
