### ISSUE TITLE
Drupal migration - cleanup tasks

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#119]
As an agency component, in order to ensure that the 2015 yml data is accurately captured in the FOIA API, I need some cleanup tasks to take place.

## Acceptance criteria

- [x] The email in the 2015 yml data should map to the submission email field in Drupal instead of the general email field (confirm with Matt)
- [x] A new `misc` field of type `foia_personnel` should be added to the agency component content type in Drupal
- [x] The `misc` field in the yml data should map to the new `misc` field
- [x] The `usa_id` field should be removed from the agency taxonomy
- [x] The `agency_component_id` field should be removed from the agency component

**Comment by Tom-Camp** [comment]
## Developer Review

- [] Check out [doj-119-tc](https://github.com/usdoj/foia/pull/66)
- [ ] Update config `drush cim`
- [ ] Log in and go to the Agency vocabulary Manage fields page `/admin/structure/taxonomy/manage/agency/overview/fields`
- [ ] Confirm that the usa_id field no longer exists.
- [ ] Go to the Agency Component content type Manage fields page `/admin/structure/types/manage/agency_component/fields`
- [ ] Confirm that the agency_component_id field no longer exists.
- [ ] Confirm that the Misc field exists below Public Liaisons.
- [ ] In a terminal, go to the src directory in the foia_migrate module `docroot/modules/custom/foia_migrate/src`
- [ ] Run the data-groomer.php `php datagroomer.php`
- [ ] The script should run without error.
- [ ] Enable the FOIA Migrate module `drush en -y foia_migrate`
- [ ] Update the foia_personnel entities `drush mi --update foia_personnel`
- [ ] You should see the message `Processed 943 items (180 created, 763 updated, 0 failed, 0 ignored) - done with 'foia_personnel'`
- [ ] Rollback the agency_component migration `drush migrate-rollback agency_component`
- [ ] Migrate the agency_components `drush mi agency_component`
- [ ] You should see the message `Processed 424 items (424 created, 0 updated, 0 failed, 0 ignored) - done with 'agency_component'`
- [ ] Go to the Content page `/admin/content`
- [ ] Search for the Title `Committee for Purchase`
- [ ] Edit the Agency Component `Committee for Purchase from People Who Are Blind or Severely Disabled`
- [ ] The Email field should be empty.
- [ ] There should be two FOIA Personnel assigned to the new Misc field.
- [ ] The Submission Email field should be populated.

**Comment by Tom-Camp** [comment]
## Functional Review

- [ ] Log in and go to the Agency vocabulary Manage fields page `/admin/structure/taxonomy/manage/agency/overview/fields`
- [ ] Confirm that the usa_id field no longer exists.
- [ ] Go to the Agency Component content type Manage fields page `/admin/structure/types/manage/agency_component/fields`
- [ ] Confirm that the agency_component_id field no longer exists.
- [ ] Confirm that the Misc field exists below Public Liaisons.
- [ ] Go to the Content page `/admin/content`
- [ ] Search for the Title `Committee for Purchase`
- [ ] Edit the Agency Component `Committee for Purchase from People Who Are Blind or Severely Disabled`
- [ ] The Email field should be empty.
- [ ] There should be two FOIA Personnel assigned to the new Misc field.
- [ ] The Submission Email field should be populated.

**Comment by malikkotob** [comment]
Looks good overall. Left some minor feedback in the PR.

**Comment by dangur** [comment]
Developer review revealed that the Misc field is 2 above the Public Liaisons field, not below as specified. Doesn't seem like a show stopper.

**Comment by kristusacquia** [comment]
UAT passed @malikkotob @Tom-Camp @dangur

**Comment by malikkotob** [comment]
Merged into `develop` and deployed to stage.
