### ISSUE TITLE
Setup queue for request form submissions that have passed validation

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#120]
As a FOIA API product owner, in order to ensure FOIA requests that need to be sent out to agency components are processed and preserved in a robust fashion, I need a queue that holds completed request form submission to be sent out.

This queue will allow the system to process requests in a more robust and efficient manner, as well as hold onto request form submissions in the event that we fail to send it via the 3rd part email service or API. Queue processing will take place in #122 

## Acceptance criteria

- [x] Create a new webform handler that enqueues submissions using Drupal's `DatabaseQueue`
- [x] Update the `foia_webform_webform_insert` implementation in `foia_webform.module` to add this handler to new webforms instead of the `foia_email` handler (we will leverage the `foia_email` handler when performing queue processing)

**Comment by Tom-Camp** [comment]
## Functional Review ##
- [ ] Login to the dev environment
- [ ] Go to the _Webform_ administration page (`/admin/structure/webform`)
- [ ] Click *+ Add webform*
- [ ] Create new form making sure that the *Use FOIA Agency template* checkbox is checked
- [ ] On the form edit page, click the *Emails / Handlers* tab
- [ ] Confirm that the *FOIA Submission Queue* is _Enabled_
- [ ] Click the *View* tab
- [ ] Fill out the form and submit
- [ ] Go to the *Recent log messages* page (`/admin/reports/dblog`)
- [ ] You should see a new message of the Type: `foia_webform` with the message *FOIA form submission added to queue.*
- [ ] To the right of that message, click *View*
- [ ] You should see your form submission

**Comment by Tom-Camp** [comment]
## Developer Review ##
- [ ] Checkout [doj-120-tc](https://github.com/usdoj/foia-api/pull/78)
- [ ] Follow _Functional Review_ steps
- [ ] Using *drush* check the queue using `drush queue-list`
- [ ] You should see `foia_form_manual_submitter  1      Drupal\Core\Queue\DatabaseQueue` in the list

**Comment by malikkotob** [comment]
Merged into `develop`.

**Comment by gsolomon123** [comment]
I successfully submitted a FOIA request and confirmed that the request arrived with a status Queued for submission. I confirmed the submission ID and content in the backstage. (I opened a separate UAT ticket, #471, regarding the request form.)
