### ISSUE TITLE
Send out request submissions to agency components via API

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#121]
As a [user], in order to [accomplish some goal], I need [some feature].

https://github.com/18F/beta.foia.gov/blob/master/agency-api-spec.md

## Acceptance criteria

- [ ]
- [ ]
- [ ]

**Comment by Tom-Camp** [comment]
## Developer Review ##
- [ ] Checkout [doj-121-tc](https://github.com/usdoj/foia-api/pull/83)
- [ ] Log in and go to the Content page ({{/admin/content}})
- [ ] Edit the _Tax Division_ Agency Component
- [ ] Change the **Portal Submission Format** to **API**
- [ ] Add _http://notanapi.com_ to the **Submission API URL** field and **Save**
- [ ] Go to the webform **Demo Form One** ({{/form/demo-form-one}})
- [ ] Edit the webform
- [ ] Click on the **Email / Handlers** sub-tab
- [ ] Remove the **FOIA email** handler
- [ ] Click **+ Add handler** and add the **FOIA Submission Queue** handler and **Save**
- [ ] Fill out the form and submit
- [ ] Run the queue worker from the terminal, `drush queue-run foia_submissions`
- [ ] You should see the following error: `Submission Service API: Agency Component: 4901. Exception code: 0. Exception message: cURL error 6: Could not resolve host: notanapi.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
Processed 1 items from the foia_submissions queue in 0.53 sec.`

**Comment by malikkotob** [comment]
Merged into `develop`
