### ISSUE TITLE
API to list agency components

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#128]
As a developer, in order to view a complete list of agencies that I can submit a FOIA, I need an API that lists out all the agency components.

This API will be used to power the agency finder UI, a typeahead search for agency component names and abbreviations. I think the response format should include the following data, but maybe json-api-ified so that our APIs are consistent.

- name
- abbreviation
- agency id
- agency name (maybe)
- agency abbreviation (maybe)

## Acceptance criteria

- [ ] API returns a list of all the agency components
- [ ] Each agency component contains the data attributes above
- [ ] API has some rough documentation
- [ ] API is public, behind api.data.gov

**Comment by adborden** [comment]
@malikkotob I just update this issue, take a look and let me know what you think.

**Comment by adborden** [comment]
https://github.com/18F/beta.foia.gov/issues/108 is the work for the agency finder UI.

**Comment by malikkotob** [comment]
Hi @adborden, I think this makes sense. One question I have is are you expecting the API to always return the full list of components? Or were you envisioning that you would filter on agency abbreviation, agency name, component name etc.?

Also, what is the agency ID? Is that the just the internal ID in drupal?

**Comment by adborden** [comment]
> 1. Are you expecting the API to always return the full list of components? Or were you envisioning that you would filter on agency abbreviation, agency name, component name etc and the results would return as appropriate?

We're using twitter's typeahead library which does support some back end fetching, but for the initial version I was thinking of just returning all the (300+) components. Any filtering would be done on the client side.

> 2. What is the agency ID? Is that the just the internal ID in drupal?

Whatever Id we would use to fetch the agency metadata... so in my stub, I've been using the agency abbreviation (e.g. `gsa` to know to fetch `/agency_components/gsa.json`). If we're sticking to the json-api format, this could be a full url in a `link` property.

> 3. Is the abbreviation the agency abbreviation, or the component abbreviation? We can do either (or both), but just a heads up that only 27 components actually had an abbreviation that was imported from the yml data.

Both (I'll update this in the description). Thinking about what the requester sees, if they type `doj`, we want them to see FBI and OIP, which means in addition to FBI having it's component abbreviation, it also needs it's agency abbreviation.

> 4. I put this request in postman together to see if what JSON API provides out of the box is what you're expecting (see the Agency Component API folder). Would you need more than this? (Minus the details in terms of specific fields to add/remove from results, and fields to filter on)

Having trouble with the Postman extension. Can you throw it in a gist or give me a curl command?

**Comment by adborden** [comment]
Just had a conversation with @vz3 and @AvivaOskow, sounds like it's important that we make a distinction between tier 1 and tier 2 agencies i.e. agencies and agency components should show up in the agency finder and you get different behavior when you select an agency vs an agency component. I'm not sure that the API needs to return a flat list, though.

**Comment by adborden** [comment]
Closing this. The existing API is working well enough. I think we could design a better design focused around search query to improve the agency finder, but that should be it's own issue.
