### ISSUE TITLE
Add agency administrator role

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#140]
As an agency administrator, in order to manage agency manager accounts, I need an agency administrator role in Drupal.

There needs to be a role that can create, edit, and delete agency manager accounts. Additionally, this role should be able to add/edit/remove all agencies and agency components.

## Acceptance criteria

- [x] Agency Administrator role created
- [x] Role can create, edit, and delete agency manager accounts (see #97)
- [x] Users with this role can add, edit, and delete all agencies.
- [x] Users with this role can add, edit, and delete all FOIA Personnel.
- [x] Users with this role can add, edit, and delete all agency components.

**Comment by dangur** [comment]
May want to use this module to limit user administration permissions https://www.drupal.org/project/roleassign

**Comment by Tom-Camp** [comment]
## Functional Review ##
- [ ] Log in as an administrator user
- [ ] From the admin menu select `People` (`/admin/people`)
- [ ] Click *Add user*
- [ ] Create a new user ensuring that the _Agency Administrator_ role is checked
- [ ] Either log out, or in a different browser, log in as the new _Agency Admin_
- [ ] Go to the _People_ page {{/admin/people}}
- [ ] In the righthand column next to the user *demo* with the role *Agency Manager* you should see `Edit`
- [ ] You should only see *Edit* to next to the user that you are logged in as and user *demo*
- [ ] Click *Edit* next to *demo*
- [ ] You should be able to edit the user
- [ ] You should also be able to delete the user by clicking *Cancel account*
- [ ] Go back to the `People` page
- [ ] Click *+ Add user*
- [ ] Under *Assignable roles* you should only see *Agency Manager* and it should be checked
- [ ] Create the new user
- [ ] Go to the _Agency_ vocabulary page (`/admin/structure/taxonomy/manage/agency/overview`)
- [ ] You should be able to *edit* or *delete* any _Agency_ term
- [ ] You should also see the *+ Add term* button
- [ ] You should be able to create a new _Agency_ term
- [ ] Go to the _FOIA Personnel entities_ admin page (`/admin/structure/foia_personnel`)
- [ ] You should be able to *edit* or *delete* any _FOIA Personnel entity_ term
- [ ] You should also see the *+ Add FOIA Personnel* button
- [ ] You should be able to create a new _FOIA Personnel entity_
- [ ] Go to the _Content_ admin page (`/admin/content`)
- [ ] You should be able to *edit* or *delete* any _Agency Component_ term
- [ ] Click the *+ Add content* button
- [ ] You should be able to create a new _Agency Component_

**Comment by Tom-Camp** [comment]
## Developer Review ##
- [ ] Checkout [doj-140-tc](https://github.com/usdoj/foia-api/pull/76)
- [ ] Update config `drush cim`
- [ ] Follow the _Functional Review_ steps

**Comment by dangur** [comment]
Reviewed (PR 76)[https://github.com/usdoj/foia-api/pull/76] and above steps.

**Comment by malikkotob** [comment]
@Tom-Camp mind adding some additional functional review steps for @kristusacquia to be able to validate the changes in permissions you made? Main functionality should be sufficient (e.g. should be able to create/edit webforms, view the toolbar etc.)

**Comment by malikkotob** [comment]
Merged into `develop`.
