### ISSUE TITLE
Create 'Request' entity to store request information

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#146]
As a site owner, in order to maintain an audit trail for all FOIA requests, I need to store high-level information about each FOIA request.

May want to store:
- status (integer field that maps to constants on the entity class definition `QUEUED`, `SUBMITTED`, `FAILED`)
- agency component (entity reference field to agency component node)
- requester email address
- when we received the submission (timestamp)
- webform sid (integer, not an entity reference, as this submission may be deleted)

Submission to component info:
- submission method (one of API or Email)
- id returned from case management system (text field)
- tracking number returned for case management system (text field)
- http code
- error code (text field)
- error message/description (text field)
- when it was submitted to the agency (timestamp)

## Acceptance criteria
- [x] Create custom 'FOIA Request' Entity to store information above with a machine name of `foia_request` (no need to make it revision-able)
- [x] Methods available on entity to update status using PHP constants (e.g. `$request->setStatus(FoiaRequestInterface::QUEUED)`)
- [x] Agency admins and managers have view-only permissions to entity
- [x] No other users have any sort of access to this entity
- [x] A view is created and available at `/foia-requests`
    - [x] Sorted by submission received date descending
    - [x] Displays request ID, agency component name, status, submission method, error code, error description, id from case management system, tracking number from case management system, webform sid, when we received the submission timestamp
    - [x] Available only to agency admins and managers
    - [x] Allows search across the request ID (entity ID), agency component name, agency name
    - [x] Allows filtering on status, submission method

## Functional Review
- [x] Login to the dev environment
- [x] Navigate to `/admin/structure/foia_request/add`
- [x] Fill out the fields and click Save
- [x] Navigate to `/admin/content`
- [x] Verify there is a `FOIA Requests` tab
- [x] Click the `FOIA Requests` tab and verify you see the request that you added
- [x] Click on the ID of the FOIA request you added and verify you are taken to the request page
- [x] Logout

*Agency Administrator Test*
- [x] Login as an user 41: `drush @foia.dev uli 41`
- [x] Navigate to `/admin/structure/foia_request/add` and verify you get an access denied
- [x] Navigate to `/admin/content`
- [x] Verify there is a `FOIA Requests` tab
- [x] Click the `FOIA Requests` tab and verify you see the request that you added previously
- [x] Logout

*Agency Manager Test*
- [x] Login as an user 36: `drush @foia.dev uli 36`
- [x] Navigate to `/admin/structure/foia_request/add` and verify you get an access denied
- [ ] Navigate to `/admin/content/foia-requests` and verify you get an access denied

**Comment by adborden** [comment]
@malikkotob when the form get's submitted, this entity will be created in the store, right? I'm expecting that on submit, drupal should do store the request and on success, and return a "confirmation id". Maybe the id of this entity. But that would allow us to put the confirmation page (doesn't exist yet) at a URL like `/request/confirmation/:confirmationId`, and to provide that confirmation id to the requester so the requester has a record of the request submission.

Can we add something like this to the AC?

**Comment by adborden** [comment]
#184 depends on this.

**Comment by malikkotob** [comment]
@adborden when the form is submitted, we will add it to a queue for processing (see #120). Then, on cron, we will claim items from the queue and send them out to agency components via api or email (see #122). At that point, if we received a 200 when sending out the email or sending via api, we will delete the submission from the database and create this request entity. If we do not receive a 200, we will place the submission back in the queue. We will need to talk through how many times we want to attempt to resubmit an item in the queue before archiving it.

**Comment by RyanSibley** [comment]
Is it also possible to store the description of records?

**Comment by adborden** [comment]
@malikkotob if we wanted to provide a user with a confirmation number, specific to the portal (not an agency FOIA tracking number), where is the best place to handle that? Because, it's likely we want to make a distinction to the requester that the Portal has received the request, but the agency has yet to acknowledge it, or maybe there was a failure and they should resubmit it.

**Comment by RyanSibley** [comment]
I see Aaron has already considered giving the confirm ID to the requester. If that is possible, do we need to store the email address beyond the time required to deliver a confirmation email?

**Comment by malikkotob** [comment]
@adborden, @RyanSibley I haven't given any thought to returning any sort of tracking number, honestly. My understanding was that as part of phase 1, the backend would not be engaging in any communication with the requester, nor would it support a tracking feature. My thought was that if the front end received a 200 from the backend's submission API (i.e. the backend successfully handled the request), that would be sufficient to display a message to the end user with a message along the lines of:

> "Your FOIA request was received by the portal and will be sent to <component_name> shortly. Further communication on your request will be handled by the agency component directly."

My thought here was that as part of phase 2 the code that generates this Request entity might also send out a note to the requester to say that that the request was sent to the component. At that point we could potentially send them the ID of the request entity, which they could use for tracking purposes, but nothing like that was discussed as being in scope for phase 1. Then the note that is presented on screen would be changed to say:

>"Your FOIA request was received by the portal and will be sent to <component_name> shortly. You will receive an e-mail when that takes place."

(or something more eloquent)

**Comment by adborden** [comment]
@RyanSibley just reminded me, the confirmation number would also be useful for agencies in order to track down a request in case something went wrong. OGE requested that a portal-specific request identifier be added to the API spec for example, I just assumed that would be tacked onto this story. It would also be useful in the email use case for the same reason.

**Comment by malikkotob** [comment]
If we want that sort of functionality we'll need to create this Request entity immediately upon submission, as you mentioned earlier. There are some architectural implications to doing this, and I'm not confident that it can be squeezed in given our timeline. I can circle back with the team so we can assess. We'll take a look at what's left on our plate and see if there is any shuffling of prioritization that can take place.

**Comment by adborden** [comment]
I think having an Id is going to be necessary for agencies to test with, so if we don't do it we're not going to be working with agencies on the API. This work could fall into that story if that makes more sense to think of it that way.

**Comment by malikkotob** [comment]
We didn't previously have a notion of an ID for agencies to use for tracking though, so I'm not sure why that would change whether or not they'd work with us on the API. If we're saying this is a pre-req to work with agencies, we're going to have to push back when we can start working with them. I'm sure we could at least start testing with a single agency without an ID. There aren't going to be a lot of requests coming in to the backend and out to them as part of testing, so it shouldn't be too difficult to manually reconcile issues.

**Comment by malikkotob** [comment]
@adborden We're essentially looking at a new ticket to refactor things. The ticket should be a relatively low lift - maybe 2 days, but I would still want OIP to sign off on it as it may take some reprioritization. Additionally, it would be nice if we could proceed with testing with an agency once we close out #121, despite the refactoring effort not being completed. I think there's value in getting started on that front sooner rather than later, especially if the ID is the only piece missing.

Here's the order we might be able to do things in to get this piece in:
- Create ticket to refactor payload built out in #121 as well as submission handling process to create this Request entity (either upon initial submission or during queue processing)
- Proceed with #121 (API work) as it is currently architected
- Work #146
- Work new refactoring ticket
- Work #122

**Comment by malikkotob** [comment]
Merged into `develop`.
