### ISSUE TITLE
Update login page to include terms of service acceptance

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#148]
As a site owner, in order to satisfy ATO requirements, I need a message added to the login page that explains the site's terms of service.

Text to add to the login page:

> You are accessing a U.S. Government information system, which includes: (1) this computer, (2) this computer network, (3) all computers connected to this network, and (4) all devices and storage media attached to this network or to a computer on this network. This information system is provided for U.S. Government-authorized use only. Unauthorized or improper use of this system may result in disciplinary action, and civil and criminal penalties.
> 
> By using this information system, you understand and consent to the following:
> \- You have no reasonable expectation of privacy regarding any communications transmitted through or data stored on this information system. At any time, the government may monitor, intercept, search and/or seize data transiting or stored on this information system.
> \- Any communications transmitted through or data stored on this information system may be disclosed or used for any U.S. Government-authorized purpose.
> 
> For further information see the Department order on Use and Monitoring of Department Computers and Computer Systems.

## Acceptance criteria

- [x] Add the above text to the Login page at `/user/login`
- [x] Attach a screenshot of the text on the login page to this story (to be sent to Brittany as part of the ATO assessment)
- [x] Adjust the `Agency Manager` role to give them permission to view the admin theme

**Comment by adborden** [comment]
@RyanSibley FYI

**Comment by Tom-Camp** [comment]
## Developer Review ##
- [ ] Checkout [doj-148-tc](https://github.com/usdoj/foia-api/pull/77)
- [ ] Clear the cache `drush cim`
- [ ] Import the config `drush cim`
- [ ] Go to the use login page (`/user/login`)
- [ ] You should see the Terms of Service below the login form

**Comment by Tom-Camp** [comment]
## Functional Review ##
- [ ] Go to the dev environment
- [ ] If you are already logged in, log out
- [ ] Go to the use login page (`/user/login`)
- [ ] You should see the Terms of Service below the login form

**Comment by Tom-Camp** [comment]
![tos](https://user-images.githubusercontent.com/2137479/30991940-8ae62c34-a464-11e7-824b-30a90019a9ab.png)

**Comment by Tom-Camp** [comment]
![tos](https://user-images.githubusercontent.com/2137479/30992040-fd0f2ae0-a464-11e7-9e95-c583a65cde22.png)

**Comment by Tom-Camp** [comment]
This was done as a block so that it can place wherever we choose.

**Comment by malikkotob** [comment]
Merged into `develop`.
