### ISSUE TITLE
Implement and style header and footer

### ISSUE THREAD

**Issue by hbillings** [18F/beta.foia.gov#152]
As a requester, in order to navigate the FOIA site, I need consistent headers and footers.

The basic design for the header is already in place. The footer is not yet implemented. 

## Acceptance criteria

- [ ] Header navigation structure finalized
- [ ] Header in place across site
- [ ] Footer implemented

**Comment by adborden** [comment]
We are thinking of just copying the CDE footer https://crime-data-explorer.fr.cloud.gov/

**Comment by hbillings** [comment]
This is sort of blocked until we finalize header IA, but I can grab the CDE footer for now.

**Comment by leahbannon** [comment]
- [ ] needs design review (sync w/ @AvivaOskow )
- [ ] needs content edit ( @RyanSibley provide list of edits)
