### ISSUE TITLE
confirmation page content

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#155]
As a requester, in order to know that my request has been received, I need to see a confirmation that my request was successfully submitted and sent to the agency.
As a requester, in order to trust the process, I need to understand what to expect next. 

The following are suggestions from the [recommendations section on Status](https://github.com/18F/foia-recommendations/blob/master/recommendations.md#status).

Steps involved in fulfilling request (generic overview)
- Identify major stages
- Write explanation for major stages
- Make it clear stages aren’t linear
- Explain that we are just passing off the request and the agency is now the place to go for status, etc.

Timeline
- Explain simple/complex
- Explain when to expect to hear from the agency
- Explain factors that affect timeline

## Acceptance criteria

- [ ] Identify necessary sections of content to fulfill user stories
- [ ] Sync with Victor
- [ ] Review with Leah

**Comment by adborden** [comment]
WIP content https://docs.google.com/document/d/11sLeV5tdrgs9F9Wvrr-iv5Pta9jcW4uvFCXlrad7Nwg/edit

**Comment by RyanSibley** [comment]
reviewed this with Aaron and we're happy with it right now. It could be edited a bit in the future but the message is accurate.

**Comment by malikkotob** [comment]
Just want to comment here to make sure there's no verbiage in the copy that mentions some sort of confirmation ID for the user. We're in the middle of some re-architecture to make that number available to the agency when we send off the request to them, but don't have things setup to provide that same number to the requester.
