### ISSUE TITLE
confirmation page

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#156]
As a requester, in order to know that my request has been received, I need to see a confirmation that my request was successfully submitted and sent to the agency.
As a requester, in order to trust the process, I need to understand what to expect next. 

## Acceptance criteria

- [ ] Implement content from #155
- [ ] implement updated content from Ryan

**Comment by AvivaOskow** [comment]
![confirmation page_1](https://user-images.githubusercontent.com/21244661/32066614-5cab8bfc-ba4e-11e7-8090-1b93e3815982.jpg)

**Comment by adborden** [comment]
Updated content https://docs.google.com/document/d/11sLeV5tdrgs9F9Wvrr-iv5Pta9jcW4uvFCXlrad7Nwg/edit
