### ISSUE TITLE
build confirmation page

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#157]
As a requester, in order to know that my request has been received, I need to see a confirmation that my request was successfully submitted and sent to the agency.
As a requester, in order to trust the process, I need to understand what to expect next. 

## Acceptance criteria

- [ ] Implement designs from #156
- [x] Pull in dynamic content from agency (header with agency name, contact info, etc. from design)
- [x] Build route from submission to confirmation page, sending data to API endpoint

**Comment by hbillings** [comment]
I believe this is unblocked, as we decided to pull in the content @RyanSibley has been working on and put it into the same sort of sidebar "template" we're using for the form itself.

**Comment by adborden** [comment]
WIP content https://docs.google.com/document/d/11sLeV5tdrgs9F9Wvrr-iv5Pta9jcW4uvFCXlrad7Nwg/edit

**Comment by adborden** [comment]
PR is ready, but we don't have the visual design yet.
