### ISSUE TITLE
implement final homepage/landing page content tweaks

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#158]
As a requester, in order to file a request, I need to understand what FOIA is, what is involved in a FOIA request process, and what other options are available for finding government info.
As a requester, in order to file a request, I need to choose the right agency and start the process.

## Acceptance criteria

- [ ] Identify additional crucial user stories for homepage w/ OIP, Leah, and Victor
- [ ] Identify necessary sections of content to fulfill user stories
- [ ] Review with Victor
- [ ] Review with Leah
- [ ] Review with OIP

**Comment by RyanSibley** [comment]
https://docs.google.com/document/d/1Vu7eLmp1trFZT6aKoAF3aEeGO2TLEncOhl5pMPcErFI/edit
