### ISSUE TITLE
Upgrade Drupal to 8.4.0

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#171]
As a site owner, in order to stay up-to-date with a supported version of Drupal, I need to upgrade to version `8.4.0`.

This release of Drupal signifies end-of-life for the version we're on (8.3.7). All versions below `8.4.0` will no longer be supported, and any releases with security patches will only be made available to version `8.4.0` and above. See [BLT's documentation](https://github.com/acquia/blt/wiki/Drupal-8.3-to-8.4-upgrade-guidance) for guidance.

## Acceptance criteria

- [x] BLT is upgraded to version `8.9.7`
- [x] Drupal is upgraded to version `8.4.0`
- [x] All automated tests are passing

**Comment by ba66e77** [comment]
https://github.com/usdoj/foia-api/pull/91

I think this is ready for review.

**Comment by malikkotob** [comment]
Merged into `develop` and deployed to staging.
