### ISSUE TITLE
design footer content

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#186]
- [ ] some required content can be found on foia.gov
- [ ] some required content can be found on [FBI CDE](https://crime-data-explorer.fr.cloud.gov/)

**Comment by RyanSibley** [comment]
<img width="626" alt="screen shot 2017-10-20 at 3 24 00 pm" src="https://user-images.githubusercontent.com/1151139/31838421-bfca98f2-b5aa-11e7-90c2-f5ff57d41588.png">
 
https://docs.google.com/document/d/1Vu7eLmp1trFZT6aKoAF3aEeGO2TLEncOhl5pMPcErFI/edit?pli=1
