### ISSUE TITLE
Update 90% template to incorporate agency feedback and use new field names

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#188]
As a portal admin, in order to ensure new agency forms are created with the latest feedback, I need to update the form template to incorporate that feedback.

We've done a lot of research around the 90% questions in interviews and survey usability. We need to update the 90% template in Drupal so new agency forms are created with the latest set.
Acceptance criteria

## Acceptance criteria

- [x] description (help text) is up to date
- [x] only the fields commonly required across agencies are marked as required
- [x] default_value (example text) is up to date
- [x] title (field labels) are up to date
- [x] certain fields are recreated to match the desired JSON output below (e.g. all address field's should have a machine name that starts with `address`)

```
{
  "address_city":"Anytown",
  "address_country":"United States",
  "address_line1":"123 Main Street",
  "address_line2":"#12",
  "address_state_province":"Alaska",
  "address_zip_postal_code":"12345",
  "company_organization": "Organization",
  "delivery_method":"electronic",
  "email":"test@tester.com",
  "expedited_processing_explanation":"",
  "fax_number":"1231234569",
  "fee_waiver_explanation":"",
  "name_first":"Test",
  "name_last":"User",
  "name_middle":"Ing",
  "phone_number":"1231234567",
  "name_prefix_title":"Mr",
  "processing_fees":"",
  "request_category":"individual",
  "request_description":"I would like information about...",
  "request_expedited_processing":"no",
  "request_fee_waiver":"no",
  "name_suffix":"Jr",
  "attachments_supporting_documentation":[{
    "content_type":"application\/pdf",
    "filedata":"",
    "filename":"another.pdf",
    "filesize":"0"
  },{
    "content_type":"application\/pdf",
    "filedata":"",
    "filename":"test.pdf",
    "filesize":"0"
  }],
  "agency":"Tax Division",
  "agency_component_name":"Tax Division"
}
```

## Functional Test
- [x] Add webform at admin/structure/webform/add
- [x] See that the titles of the elements correspond to the titles in https://docs.google.com/a/gsa.gov/document/d/1db58HqeTgkhRQ0dqChKQ-wo3LWgL9temn956OJfLPxo/edit?usp=sharing
- [x] Verify that the help text for each of the elements matches the help text outlined in the above google doc (You can view help text for elements that have them by hovering over the question marks)

## Developer Test
- [x] Code review [PR 97](https://github.com/usdoj/foia-api/pull/97)

### Setup
- [x] Checkout doj-188-dg
- [x] Import config `drush cim`
- [x] Reload caches `drush cr`

### Test
- [x] Verify that the element machine names correspond to the updated agency [API Spec](https://github.com/18F/beta.foia.gov/pull/110/files)
- [x] Review functional test steps
- [x] Run automated tests `blt tests`
- [x] See 28 scenarios (28 passed) 314 steps (314 passed)
- [x] See that all unit tests pass

**Comment by adborden** [comment]
Can we also `s/suffix/name_suffix/`, `s/prefix_title/name_prefix_title/` please?

**Comment by adborden** [comment]
Not sure if it makes sense to do this work together, but want to call out https://github.com/18F/beta.foia.gov/issues/198 is also about updating this template.

**Comment by malikkotob** [comment]
@adborden I think it's a good idea to work these together. Let's choose a single one of these tickets and include all of the updates needed to the template in the one. That should make the development process easier.

**Comment by RyanSibley** [comment]
@malikkotob https://docs.google.com/a/gsa.gov/document/d/1db58HqeTgkhRQ0dqChKQ-wo3LWgL9temn956OJfLPxo/edit?usp=sharing

Let me know if you'd like to pair on this. Also, I can't call this copy final until OIP reviews it, but assuming there's opportunity for editing in the future, the copy in the doc above should be good to use.

**Comment by malikkotob** [comment]
@RyanSibley, @dangur is working on this so he'll be reaching out to you in the event that he has questions. I think our preference is that we only deploy these changes once, so before we ship off the code we'll put things on hold pending OIP review. Do we have an estimate on when that might be?

**Comment by adborden** [comment]
Sounds great. I just want to point out that the design team hasn't had much opportunity to look at how the form is actually being rendered until recently so I appreciate everyone's patience as we work to get this right.

**Comment by dangur** [comment]
Here's how the form looks in Drupal with default values: ![test___foia_gov](https://user-images.githubusercontent.com/307044/31896442-c7f98748-b7e1-11e7-84e8-7610581a1438.png)

**Comment by dangur** [comment]
@RyanSibley Here is what the elements look like: 
![test___foia_gov](https://user-images.githubusercontent.com/307044/31896643-509adb1a-b7e2-11e7-86c3-3f2134188f97.png)

**Comment by dangur** [comment]
Here are the updates based on today's conversations: 
![dfs___foia_gov](https://user-images.githubusercontent.com/307044/31911132-af8b7dca-b80d-11e7-81d8-fcd35cfe0305.png)
![dfs___foia_gov](https://user-images.githubusercontent.com/307044/31911148-b7e25944-b80d-11e7-9e92-9154e61b4baf.png)

**Comment by RyanSibley** [comment]
I had a meeting with Matt and this is what we have so far: https://docs.google.com/document/d/1db58HqeTgkhRQ0dqChKQ-wo3LWgL9temn956OJfLPxo/edit

We made changes throughout. 

We're confirming with Bobby tomorrow to make sure we've covered everything. Thanks for your patience. 

Another question: Is it possible to have help text visible rather than behind tooltips? Maybe in smaller, italicized text?

**Comment by adborden** [comment]
@RyanSibley for help text, yes, we can control that on the front stage.

Hmm, previewing the changes here will be problematic. What you're looking at in these screenshots are the drupal back end, which requesters won't see, so it's not a great representation.

@dangur not sure if you can grab screenshots of the front stage form? If these changes are merged to the dev environment then you would be able to see them from http://foiafrontdev.prod.acquia-sites.com/request/ 

Unfortunately none of the agencies in the dev environment have a form yet.

**Comment by dangur** [comment]
@adborden I'm not seeing much at http://foiafrontdev.prod.acquia-sites.com/request/, just an autocomplete with agency components.

**Comment by adborden** [comment]
@dangur that's right, if you know of any agencies with a form on dev, you should select that and then you would see the rendered form.

**Comment by dangur** [comment]
Here's what I have now on the Drupal side: 
![v___foia_gov](https://user-images.githubusercontent.com/307044/31962576-efd572c8-b8cb-11e7-99c4-24f5c84f7eb6.png)
![v___foia_gov](https://user-images.githubusercontent.com/307044/31962773-7966163c-b8cc-11e7-9799-feb3b196b3c1.png)

**Comment by dangur** [comment]
Here's what I have now in Drupal:
![v___foia_gov](https://user-images.githubusercontent.com/307044/31963363-608e2e18-b8ce-11e7-9604-79d94ce9e6ed.png)
![v___foia_gov](https://user-images.githubusercontent.com/307044/31963380-6f0d92ee-b8ce-11e7-939d-4d0ff7ff933a.png)

**Comment by RyanSibley** [comment]
Per our discussion earlier, I'll add text to fields that should be left blank if a requester selects no for fee waivers or expedited processing. 

Regarding defaults, all yes/nos should be set to no. Also, just to be clear, I am expecting drop downs and not radio buttons. 

The country field should also default to the United States.

**Comment by dangur** [comment]
I added those defaults and moved zip/postal code above country...
![m___foia_gov](https://user-images.githubusercontent.com/307044/31965377-37d78fc6-b8d5-11e7-846a-44616c533eae.png)
![m___foia_gov](https://user-images.githubusercontent.com/307044/31965392-4391a2f2-b8d5-11e7-99b1-80333de4ab06.png)

**Comment by malikkotob** [comment]
@adborden are the machine names from the screen shot above okay? If so, do you want to update the PR for the api spec to match these?

Actually, one thing I just realized..
@RyanSibley, looks like we DID already have a field for the amount someone was willing to pay, it was just titled "Processing Fees" (see screenshot above). Are we save to remove that one in favor of the new "Please tell us the amount of money you're willing to pay" field?

cc @dangur

**Comment by dangur** [comment]
I thought `processing fees` was what the agency component would set as the standard fee and the `amount willing` would be a counteroffer by the requester.

**Comment by malikkotob** [comment]
@dangur hmm I don't think so, this form isn't touched by the component. It's just filled out by requesters.

**Comment by RyanSibley** [comment]
Thanks for changing it away from processing fees. What you have now is
confirmed by OIP. And @dangur, yeah, there is no set fee by an agency. It
seems like it's all negotiable with the goal to charge as little as
possible, hopefully. :)

**Comment by dangur** [comment]
I deleted the processing_fees field, since it will be handled in the fee_amount_willing field. Help text has been updated as well.

**Comment by malikkotob** [comment]
Merged into `develop`
