### ISSUE TITLE
Import annual processing data from scrapers

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#192]
As a Portal admin, in order to keep the processing data that requesters see during the request process up to date, I need the yaml import script to update agency components with the annual reporting data from the scrapers.

## Acceptance criteria

- [x] If the agency component does not exist in the Drupal repo, create it with the current contact data
- [x] If the agency component already exists, do not modify any of its fields, only update the processing data
- [x] Processing data should not be exposed via the agency info updater tool (it's okay if admins can access it)
- [x] It's okay if the import job clobbers any edits to the processing data in the Drupal repo, it is not okay to clobber edits to the agency component contact data

## Technical Requirements
- [x] Add processing data fields (text fields) to component content type
- [x] Include a 'year' field
- [x] All processing data fields should live within a field group
- [x] All processing data fields should be read-only for all users
- [x] Update `data-groomer.php` to add 2016 data to `components.json`
- [x] Write new script to pull in processing data field (perform migration lookup as part of script to find existing components)

## Functional Review
- [x] Login to the dev environment as an agency administrator using drush: `drush @foia.dev uli 41`
- [x] Go to http://foiadev.prod.acquia-sites.com/node/4611
- [x] Verify you see a Request Data Year of `2009`
- [x] Click the "Edit" tab, and verify that you do not see any of the following fields available for edit:
```
Complex Average Days
Complex Highest Days
Complex Lowest Days
Complex Median Days
Simple Average Days
Simple Highest Days
Simple Lowest Days
Simple Median Days
Request Data Year
Expedited Average Days
Expedited Highest Days
Expedited Lowest Days
Expedited Median Days
```
- [x] Go to http://foiadev.prod.acquia-sites.com/node/4501
- [x] Verify you see the stats below:
```
Complex Average Days
136.31
Complex Highest Days
1741
Complex Lowest Days
less than 1
Complex Median Days
47
Simple Average Days
36.55
Simple Highest Days
1194
Simple Lowest Days
less than 1
Simple Median Days
13
Request Data Year
2016
Expedited Average Days
36.71
Expedited Highest Days
485
Expedited Lowest Days
less than 1
Expedited Median Days
5

```
## Developer Review
- [x] Code review [PR 95](https://github.com/usdoj/foia-api/pull/95)
### Setup
- [x] Checkout branch `doj-192-dg` locally
- [x] Import a fresh db `blt sync:db`
- [x] Import config `drush cim`
- [x] Enable `foia_migrate` module: `drush en foia_migrate -y`

### Test
- [x] Run the migration `drush mi processing_data`
- [x] See `Processed 424 items (424 created, 0 updated, 0 failed, 0 ignored) - done with 'processing_data' [status]`
- [x] Complete Functional Review steps
- [x] Run the automated tests `blt tests:behat -D behat.paths=AgencyComponent.feature`
- [x] Roll migration back `drush mr processing_data`
- [x] See `Rolled back 424 items - done with 'processing_data' [status]`
- [x] Run the migration again `drush mi processing_data`

**Comment by adborden** [comment]
cc @malikkotob

**Comment by malikkotob** [comment]
@kristusacquia functional review steps are ready for you to complete in the dev environment.

**Comment by malikkotob** [comment]
Merged into `develop`.
