### ISSUE TITLE
API should return complete list of options for webform elements

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#195]
Some webform elements that are select type include an options that is a string instead of an options object.
```
 "country": {
    "#type": "select",
    "#title": "Country",
    "#default_value": "United States",
    "#options": "country_names"
  }
```

In order to render and validate the form properly, we need to know what the list of `country_names` that are available.
 
## Expected Behavior
`#options` is an object, e.g
```
  "#options": {
    "us": "United States",
    "uk": "United Kingdom"
  }
```

## Actual Behavior
```
 "country": {
    "#type": "select",
    "#title": "Country",
    "#default_value": "United States",
    "#options": "country_names"
  }
```

## Steps to reproduce the behavior

    $ curl 'http://local.dojfoia.gov/jsonapi/agency_components/e8681f4b-1484-4128-b9b2-d78cd6c7b888?_format=api_json&include=request_form' | jq  '.included[0].attributes.elements.country'

**Comment by adborden** [comment]
As a work-around, @malikkotob provided some of the options for these effected fields are here: https://gsa-tts.slack.com/files/U69SSL6HY/F7H7AB423/-.txt

**Comment by malikkotob** [comment]
@adborden is this something you see as a higher priority? Maybe we can discuss tomorrow since there were several issues opened.

**Comment by malikkotob** [comment]
## Functional Review
N/A

## Developer Review
- [ ] Review [PR 90|https://github.com/usdoj/foia-api/pull/90]

*Setup*
- [ ] Checkout `doj-195-dg` locally
- [ ] Clear caches: `drush cr`

*Testing*
- [ ] Hit the jsonapi endpoint using the below command and verify that predefined webform options (e.g. country/state) are fully rendered and not simply a machine name
```
curl 'http://local.dojfoia.gov/jsonapi/agency_components/e8681f4b-1484-4128-b9b2-d78cd6c7b888?_format=api_json&include=request_form' | jq  '.included[0].attributes.elements.country'
```

**Comment by malikkotob** [comment]
@adborden, fyi this was merged into `develop`!
