### ISSUE TITLE
Update 90% questions with help text, field labels, and required status

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#198]
We've done a lot of research around the 90% questions in interviews and survey usability. We need to update the 90% template in Drupal so new agency forms are created with the latest set.

## Acceptance criteria

- [ ] description (help text) is up to date
- [ ] only the fields commonly required across agencies are marked as required
- [ ] default_value (example text) is up to date
- [ ] title (field labels) are up to date

**Comment by adborden** [comment]
@RyanSibley @malikkotob I'm not sure if you want to work off a google sheet for this info or pair on this, but I wanted to get this on your radar.

**Comment by malikkotob** [comment]
Duplicate of #188.

@adborden, @RyanSibley I added the AC from this ticket to #188 and am closing this one out.
