### ISSUE TITLE
finalize agency search design

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#205]
## Acceptance criteria

- [ ] people can find agency and sub-agencies
- [ ] people can tell which agency a sub-agency belongs to
- [ ] display agency information when agency is selected
- [ ] display list of sub-agencies when a top-level agency is selected

**Comment by AvivaOskow** [comment]
Once the user has selected an agency:

![foia_agency preview for dev_10 20 17](https://user-images.githubusercontent.com/21244661/31845310-7f82de44-b5cd-11e7-81ed-d39bd5a7c05d.jpg)

**Comment by AvivaOskow** [comment]
Updated designs in #221
