### ISSUE TITLE
form sections design

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#216]
- [x] split form up into sections
- [x] finalize descriptions of sections

**Comment by RyanSibley** [comment]
https://docs.google.com/a/gsa.gov/document/d/17QkHrbrhaR3Tw7gzgjrgDjxIGkZXTkymD5AMFq7ZqOw/edit?usp=sharing

**Comment by RyanSibley** [comment]
Waiting on copy from Bobby and Matt for the processing fees and expedited processing section.

**Comment by leahbannon** [comment]
- [ ] Received feedback from OIP, implementing/editing now
- [ ] Ping Heather when ready

**Comment by RyanSibley** [comment]
@hbillings here's the text for the sections: https://docs.google.com/a/gsa.gov/document/d/17QkHrbrhaR3Tw7gzgjrgDjxIGkZXTkymD5AMFq7ZqOw/edit?usp=sharing
