### ISSUE TITLE
Select a decentralized agency in the agency finder

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#221]
As a requester, in order to understand how to submit a FOIA request to a decentralized agency, I need the agency finder to list out the agency mission and its comprising agency components.

When you select an agency from the agency finder, you should see the agency's name, mission, and agency components appear below the agency finder.

## Acceptance criteria

- [x] Decentralized agencies appear as suggestions in the agency finder
- [x] Selecting a decentralized agency in the agency finder closes the agency finder suggestions window and displays the agency information below
- [x] The agency information includes the agency name, mission, and it's agency components

**Comment by leahbannon** [comment]
- [ ] need final design mock
- [ ] implement changes
- [ ] pair to review

**Comment by AvivaOskow** [comment]
**Parent agency**
<img width="543" alt="screen shot 2017-10-26 at 1 07 37 pm" src="https://user-images.githubusercontent.com/21244661/32066719-b17947a0-ba4e-11e7-8d36-c59f8c65b5db.png">


**Agency component**
<img width="682" alt="screen shot 2017-10-25 at 2 41 29 pm" src="https://user-images.githubusercontent.com/21244661/32066671-8e35e460-ba4e-11e7-803a-3a4ce949ca5e.png">

**Comment by leahbannon** [comment]
- implement carrot
- design review
