### ISSUE TITLE
Create plan for archiving and redirecting legacy pages

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#225]
As a [user], in order to find information that has been moved to a new URL, I need to be redirected to a functioning URL, likely the FOIA.gov homepage. 

[Description, background context, or implementation details]

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by adborden** [comment]
Here's how I'm thinking this will work. Folks who have https://www.foia.gov/report-makerequest.html bookmarked, they will see [this](http://foiafrontdev.prod.acquia-sites.com/report-makerequest.html) on the new foia.gov. We can add a banner for different pages with something like "this content has moved to X" or "this page is in transition, but the content is still accurate", or whatever. We can do page-specific banners depending on the situation.
