### ISSUE TITLE
Create beta bar

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#226]
As a [user], in order to know that FOIA.gov is going to continue to improve, I need a beta bar or other design to indicate that.

[Description, background context, or implementation details]

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by leahbannon** [comment]
I think this can address #227 for feedback mechanism if we add something like "Questions or comments? Email us at [oip foia email]."

**Comment by RyanSibley** [comment]
email address for feedback:  National.FOIAPortal@usdoj.gov

**Comment by RyanSibley** [comment]
Content in progress: https://docs.google.com/a/gsa.gov/document/d/1hzt4GKgx6RvIPSZ4dDIyXiu3iMghWzb50FtZTkbvyc8/edit?usp=sharing

**Comment by RyanSibley** [comment]
this is where I'm deciding what pages get what treatment: https://docs.google.com/spreadsheets/d/12LdK_BjmzGuvTVzcNxicui_Zzo8BOLkN-2dAf9XBWGo/edit?pli=1#gid=0

**Comment by AvivaOskow** [comment]
**Initial feedback banner**
<img width="887" alt="screen shot 2017-11-06 at 1 15 50 pm" src="https://user-images.githubusercontent.com/21244661/32456786-d10e8068-c2f4-11e7-95eb-af6436dfabed.png">

**Closed feedback banner**
<img width="885" alt="screen shot 2017-11-06 at 1 16 44 pm" src="https://user-images.githubusercontent.com/21244661/32456831-f49db60c-c2f4-11e7-810e-17000bc25065.png">

**Archived page banner**
<img width="882" alt="screen shot 2017-11-06 at 1 17 03 pm" src="https://user-images.githubusercontent.com/21244661/32456844-ffeacb9e-c2f4-11e7-9eb6-fa6c3206a8ab.png">
