### ISSUE TITLE
add content to reflect availability of contact info and that some agencies not interoperable

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#231]
As a a requester or agency personnel, in order to find contact information or know that I'm going to need to submit my request on another website, I need content that tells me that below the agency search on the homepage.

[Description, background context, or implementation details]

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by leahbannon** [comment]
Related to this interaction interaction in #235

**Comment by RyanSibley** [comment]
Added to the landing page before an agency is selected:

> Not all agencies can receive FOIA requests created on FOIA.gov. The information for where to submit a request to those agencies will be available after you select an agency above.
