### ISSUE TITLE
provide links to FOIA portals and agencies that are not interoperable with foia.gov

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#235]
As a [user], in order to submit a FOIA request to an agency that is not interoperable with FOIA.gov, I need a link or to be redirected automatically to that agency's existing portal or website.

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by leahbannon** [comment]
Plz verify:
Anticipated user flow:
- user selects agency that isn't interoperable yet
- user sees 1. agency metadata as normal 2. standard text (from Ryan) about non-interoperability 3. custom info with link or other info about alternative option for FOIAing agency

**Comment by vz3** [comment]
@leahbannon That looks right to me. It may be worth considering a callout design for this and for out-of-date content.

**Comment by adborden** [comment]
@RyanSibley do you have any copy for this?

**Comment by RyanSibley** [comment]
@adborden yes -- it currently lives on the landing page below the agency selector bar:
 

> Some agencies have existing FOIA portals and will continue to receive requests through their current portals while they work towards becoming interoperable with FOIA.gov.   The information for where to submit a request to those agencies will be available after you select an agency above. 

^^Above is this most recent version. OIP sent over edits yesterday, so what's in the repo needs to be changed to reflect this. 

https://docs.google.com/document/d/1Vu7eLmp1trFZT6aKoAF3aEeGO2TLEncOhl5pMPcErFI/edit?ts=59fb683e

**Comment by RyanSibley** [comment]
To address what people see after clicking on an agency that isn't linked to FOIA.gov, we should add:

> Currently, this agency's FOIA process is not linked to FOIA.gov. You can submit a request to this agency using the information found at [web address](link).

**Comment by adborden** [comment]
I'll grab @AvivaOskow to walk through this with her.
