### ISSUE TITLE
do a final review of footer content

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#241]
As a [user], in order to [accomplish some goal], I need [some feature].

[Description, background context, or implementation details]

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by RyanSibley** [comment]
These are the contents -- I'm gathering the specifics now: 
<img width="695" alt="screen shot 2017-10-25 at 10 17 26 am" src="https://user-images.githubusercontent.com/1151139/32003653-bfb140ca-b96d-11e7-9222-ca428c9da904.png">
