### ISSUE TITLE
Make confirmation page printable

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#250]
As a [user], in order to keep the summary of my request on file, I need the confirmation page to be printable.

[Description, background context, or implementation details]

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by adborden** [comment]
Does this need design? The print view we're thinking of includes
- [ ] site header
- [ ] submission ID at the top of the page
- [ ] sidebar is hidden

**Comment by RyanSibley** [comment]
@AvivaOskow what do you think?
