### ISSUE TITLE
Implement iconography

### ISSUE THREAD

**Issue by hbillings** [18F/beta.foia.gov#255]
As a requester, in order to get a hint about the theme of a piece of repeated information, I need visual cues like icons.

Acceptance criteria:
- [ ] Implement icons on homepage (64px round)
- [ ] Adjust spacing on homepage to match (32px padding above/below text divider and icons)
- [ ] Implement icons on request form
- [ ] Implement icons on confirmation page

**Comment by adborden** [comment]
This is covered by #237
