### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by hbillings** [18F/beta.foia.gov#256]
This is a running list of design tweaks that don't fit into a particular story.

## Sitewide
- [x] Link bottom border should be 2px
- [x] Implement global styles for forms that include no border and darkest blue text
- [x] Glossary button should be bold and also `$color-primary-alt-light`
- [x] Update logo to one with correct colors
- [x] Visited link styles should be dark blue always
- [x] favicon?

## Landing page
- [x] Implement new content for landing page
- [x] Submit a request button should be `$color-primary-alt-light`
- [x] Submit a request button text should not be white
- [x] Add a couple extra pixels padding on the `p` tags in the three column layout
- [x] Need to be able to exit dropdown menus by clicking outside them
- [x] Research section titles line height needs adjustment
- [x] Research section columns need extra padding in gutter
- [x] Move gov resources from first menu to second

## Nav
- [x] Use thick bar as focus state indicator for nav, drop focus box and drop border bottom as hover state
- [x] Dropdown: lightest blue for background, second-lightest for hover
- [x] In new WDS, the text is white on focus

## Legacy grid
- [x] Add legacy grid to pages that needs it
- [x] Legacy content needs to align with either the nav or the logo
- [x] 1 px lightest blue line on `grid-legacy`
- [x] Hover state on logo on legacy pages has a jquery tooltip

## Decentralized agency preview
- [x] Carat on decentralized agency list

## Agency component preview
- [x] On child agency previews, link parent agencies' heads to the list of all that agency's children
- [x] Create an external link indicator
- [x] More space around the search bar, to get the blue bar up to the top of the screen
- [x] Reduce space between address lines
- [x] Round average processing time

## Request form
- [x] Tabs are bizarre at half size
- [x] Sidebar should be the same size throughout until it gets mobile
- [x] Secondary mobile menu like CDE
- [x] Max width on body copy
- [x] Form content is 6 cols
- [x] Form should have a gutter and a column and a gutter between it and the sidebar. Is there an offset in WDS 1.3.1?
- [x] On form, "Make your request" should replace the agency name at top
- [x] Form heds should be in Merriweather
- [x] Make sure we're loading Merriweather semibold
- [x] Required field doesn't match desired styles
- [x] Restyle list of sections so it looks like list of navigation links
- [x] Add blue box around section info
- [x] Space between form fields needs to adjust
- [x] Aviva needs to adjust field description styling (needs to always be there, not go away when you click on it)
- [x] Style choose file button, is it possible?
- [x] Add final step for reviewing before you submit
- [x] glossary links in section help content coming in PR soon
- [x] glossary links in field-level help content
- [x] Prioritize issue for error handling/field level errors
- [x] Upload progress indicator is missing the updated button classes

**Comment by hbillings** [comment]
There are indeed offsets in USWDS now. Guidance for using them can be found here: https://components.standards.usa.gov/components/detail/grid--offsets.html

**Comment by adborden** [comment]
@RyanSibley ^
