### ISSUE TITLE
Request form visual design

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#265]
- [ ] nav/progress bar
- [ ] form
- [ ] design review issues in https://github.com/18F/beta.foia.gov/issues/265 for the request form are addressed or additional issues are created.

**Comment by RyanSibley** [comment]
https://docs.google.com/a/gsa.gov/document/d/17QkHrbrhaR3Tw7gzgjrgDjxIGkZXTkymD5AMFq7ZqOw/edit?usp=sharing

**Comment by AvivaOskow** [comment]
![foia_form_11 1 17](https://user-images.githubusercontent.com/21244661/32283016-9dae2fe2-bef9-11e7-896a-520ffb20c49f.jpg)

**Comment by adborden** [comment]
This issue should cover the design tweaks under "Request form" in https://github.com/18F/beta.foia.gov/issues/256, adding to the description.
