### ISSUE TITLE
Attachments submitted in request form are not persisted in Drupal

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#272]
Attachments in the form do not appear to be saved in drupal. The request is successful.

I believe this is on the front stage, we might not be formatting the payload properly. The API should probably give an error.

## Expected Behavior
Should be able to see the attachment data in the drupal admin.

## Actual Behavior
attachement_supporting_documentation is empty.

## Steps to reproduce the behavior

1. Open a [form](http://foiafrontdev.prod.acquia-sites.com/request/agency-component/db0d3e3f-7280-4a42-864f-94aa90f5c4e8/)
1. Fill out the required fields
1. Choose an attachment
1. Click submit
1. Check the [submissions](http://foiadev.prod.acquia-sites.com/admin/structure/webform/manage/fema_test_form/results/submissions)
1. Check your submission for the attachment field

**Comment by malikkotob** [comment]
@adborden I do see some warnings in the logs where the code attempts to create the files. It's hard to tell what's going on though. Do you have a sample payload I could take a look at that the front stage generates?

**Comment by adborden** [comment]
Right now, the front end is sending a string for the attachment field, a data url like `data:image/png;name=foo.png;base64,asjfjklsajfkldjsalkfds==`, but it should be sending an object. File size is hard to get, but we will be splitting that data url to
```json
{
  "content_type": "image/png",
  "filename": "foo.png",
  "filedata": "asdjkfljlksaf=="
}
```
