### ISSUE TITLE
Explore content+design around a warning for legacy content

### ISSUE THREAD

**Issue by vz3** [18F/beta.foia.gov#277]
As a FOIA.gov visitor, in order to know why some legacy content might be broken, outdated, or look weird, I need some sort of warning indicating why that is the case.

Warning for legacy content. Thinking a small modal-style warning for legacy content. The need for this should be validated by @RyanSibley and cleared through OIP.

## Acceptance criteria

- [x] Copy for a warning for legacy content
- [x] Design for a warning for legacy content
- [x] Warning appears on legacy pages

**Comment by leahbannon** [comment]
Possibly similar content to #275

**Comment by adborden** [comment]
Content here: https://docs.google.com/document/d/1hzt4GKgx6RvIPSZ4dDIyXiu3iMghWzb50FtZTkbvyc8/edit

**Comment by adborden** [comment]
Designs are mixed with the beta bar in #226

**Comment by adborden** [comment]
We want to allow pages to override the content for this banner. Specifically, this page http://foiafrontdev.prod.acquia-sites.com/report-makerequest.html should direct visitors to the search box on the landing page.
