### ISSUE TITLE
remove search add glossary link in header

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#278]
Possibly with an icon like this? 

<img width="116" alt="screen shot 2017-10-27 at 9 47 36 am" src="https://user-images.githubusercontent.com/4323988/32115494-e6afcaae-bafb-11e7-895c-a7b4cd4d5f7a.png">

**Comment by adborden** [comment]
I think we can close this, we seem to like the glossary button fixed to the bottom of the screen.
