### ISSUE TITLE
Add search button to typeahead

### ISSUE THREAD

**Issue by hbillings** [18F/beta.foia.gov#282]
As a user, in order to search for an agency, I need a search button.
The agency preview search is functional without the search button, but it feels weird not to have that interactive component. It also helps label the input.

## Acceptance criteria

- [ ] There's a search button

**Comment by hbillings** [comment]
If the button turns out not to be a great idea, maybe we could do something like this instead:
<img width="923" alt="screen shot 2017-10-28 at 9 29 57 am" src="https://user-images.githubusercontent.com/509309/32135830-a4e238b0-bbc2-11e7-99e6-7a325a3b7ba1.png">

**Comment by hbillings** [comment]
Nonfunctional button:
<img width="921" alt="screen shot 2017-10-28 at 9 35 59 am" src="https://user-images.githubusercontent.com/509309/32135890-75c845b4-bbc3-11e7-98b2-c27f060d6a43.png">

**Comment by adborden** [comment]
This was done in https://github.com/18F/beta.foia.gov/pull/284
