### ISSUE TITLE
Agencies modal on /data.html appears empty

### ISSUE THREAD

**Issue by brockfanning** [18F/beta.foia.gov#291]
As an anonymous user, in order to use the /data.html page to get reports, I need be able to be able to select an agency.

Currently, on /data.html, clicking the text box under "Select agency" displays an empty modal. The same thing happens when clicking "Show list of agencies".

Maybe a clue is this javascript error that happens on page load:

```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at getListAgencyinPage (agencyWork.js:171)
    at data.html:612
```

## Expected Behavior

![foia-data-agencies-modal](https://user-images.githubusercontent.com/1319083/32236633-203f5592-be39-11e7-9499-45df018335ca.png)

## Actual Behavior

![foia-data-agencies-modal-broken](https://user-images.githubusercontent.com/1319083/32236626-1947a03c-be39-11e7-918b-7febbc9019cc.png)

## Steps to reproduce the behavior

1. Go to /data.html
1. Click in the text box under "Select agency"

**Comment by adborden** [comment]
This should be fixed by #290
