### ISSUE TITLE
Uploaded filename not saved in react-jsonschema

### ISSUE THREAD

**Issue by hbillings** [18F/beta.foia.gov#296]
The mocks call for showing the name of the uploaded supporting documentation on the confirmation page, but the way `react-jsonschema-form` works seems to only provide the base64-encoded string as an attachment. (There does seem to be a `name` attribute encoded there, at least in Chrome, but I'm not sure how wise it is to rely on that.)

We either need to figure out how to add a name attribute or rework the design to not need the filename.

**Comment by adborden** [comment]
@hbillings I've started working on a fix for this as part of https://github.com/18F/beta.foia.gov/issues/272 let me know if you wan to pair on it.

**Comment by hbillings** [comment]
@adborden Sweet! I've got my hands full with plenty of other stuff, heh.
