### ISSUE TITLE
Metadata API returns 500 when X-Forwarded-Host is included

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#297]
When configuring api.data.gov in https://github.com/18F/beta.foia.gov/issues/111, we set the `X-Forwarded-Host` header to the API knows what Host to use in the API links. Including this header results in a 500.

## Steps to reproduce the behavior

https://gist.github.com/adborden/9f61ab8098e88c01267d7495788df2ce

**Comment by adborden** [comment]
cc @malikkotob

**Comment by ba66e77** [comment]
@adborden, I believe we've resolved this.  Can you give it another test, please?

**Comment by adborden** [comment]
@ba66e77 awesome, looks good, thank you!

**Comment by malikkotob** [comment]
@adborden mind testing in the staging environment as well with `stg-api.foia.gov` as the host? If it works, we can close this out!

**Comment by adborden** [comment]
Yep, staging is looking good, too, thanks!
