### ISSUE TITLE
Programmatically create request form submissions

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#91]
As a [user], in order to [accomplish some goal], I need [some feature].

With request forms being submitted outside of Drupal rather than directly on the site, submissions will need to be created and stored programmatically through an exposed request form submission API.

## Acceptance criteria

- [x] An API endpoint at `/api/webform/submit` exists
- [x] The endpoint accepts a `JSON` payload containing an `id` (this is the webform ID, found in the exposed agency metadata API on a per-component basis), as well as submission data keyed by webform field names (also found in the metadata)
- [x] The endpoint validates submission attempts against the webform being submitted against
- [x] Webform submissions are created for valid submission attempts
- [x] The endpoint returns the submission id upon for successful submissions

**Comment by malikkotob** [comment]
## Functional Review
N/A

## Developer Review
- [ ] Review [PR #69](https://github.com/usdoj/foia/pull/69)

*Setup*
- [ ] Check out {{doj-91-mk}} locally
- [ ] Import config to enable the `syslog` module and adjust the attachment field settings on the webform template: `drush cim`
- [ ] Clear caches

*Manual Testing*
- [ ] Use the run in postman button below to access a collection containing a well-formed request
- [ ] The request can be found under the 'Request Form submission' folder and is titled 'Custom Webform Submission Endpoint'
- [ ] Test the following scenarios using postman:
  - [ ] Submit the request as is and verify you receive a `201` response containing a submission ID
  - [ ] Submit the request without an `id` and verify the submission is rejected
  - [ ] Submit the request with an `id` of `non-existent` and verify the submission is rejected
  - [ ] Submit the request with an `id` of `contact` and verify the submission is rejected (that form is not associated with a component)
  - [ ] Submit the request without one of the form's required fields (e.g. `first_name`) and verify the submission is rejected with an appropriate reason
  - [ ] Submit the request with an invalid e-mail address and verify the submission is rejected with an appropriate reason
  - [ ] Submit the request with a file name of `cv.exe` instead of `cv.pdf` and verify the submission is rejected due to restrictions on the permitted file extensions
  - [ ] Modify the max filesize for the attachments field on the webform being submitted against to `1 MB` and verify you are unable to submit a file larger than that (note: you'll need to base64 encode data and paste it into the `filedata` entry for one of the file attachments)

*Postman*
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/81fd4336749411ffffb3)

*Automated Testing*
- [ ] Run blt:tests-all to ensure no existing tests broke

**Comment by malikkotob** [comment]
Covers #92

**Comment by ba66e77** [comment]
I left a few comments on the PR but nothing blocking.  I noticed two other items though.  The latter (filename) we should probably consider a blocker.

1. When using an unsupported file type for the upload, it works as expected.  However, do we really want to allow all these types? A DMG?

> "Only files with the following extensions are allowed: <em class=\"placeholder\">gif jpg png bmp eps tif pict psd txt rtf html odf pdf doc docx ppt pptx xls xlsx xml avi mov mp3 ogg wav bz2 dmg gz jar rar sit svg tar zip</em>."

2. Files display with the name given in the filename field but the actual name of the file on disk is the submission id (e.g., 7 or 7_0)

**Comment by malikkotob** [comment]
Good catches, @ba66e77.

1. I do not think we want to allow these types. Those are the default, but we haven't yet found out what types we should be allowing. Maybe I'll update for now to assume we only want to allow the following:
```
gif jpg png txt pdf doc docx
```
@adborden, thoughts here? Should we create a separate ticket for this?

2. Fix for this coming in the PR. Good catch.

**Comment by adborden** [comment]
I'm asking agencies what kind of file types they allow in their case management systems and in email but haven't gotten any data back yet. I think we should use your list for now, plus `odf` ;)
```
gif jpg png txt pdf doc docx odf
```

Any feedback that comes out of https://github.com/18F/beta.foia.gov/issues/85, we'll create additional stories at that point.

**Comment by malikkotob** [comment]
@ba66e77 feedback incorporated from here and the PR, https://github.com/usdoj/foia/pull/69 is ready to review again.

**Comment by ba66e77** [comment]
Reviewed and approved. ![ship it squirrel](http://dougbelshaw.com/blog/wp-content/uploads/2013/10/ship-it-squirrel.jpg)

**Comment by malikkotob** [comment]
Merged into `develop` and released to the staging environment.

@adborden you should be able to use the postman button above to see what the interaction is like.
