### ISSUE TITLE
Send request submissions via email using Drupal's core mailing capabilities

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#94]
As a [user], in order to [accomplish some goal], I need [some feature].

[Description, background context, or implementation details]

## Acceptance criteria

- [x] Contents of a request submission are emailed to a specified email address

**Comment by dangur** [comment]
##Technical Requirements
[ ] The {{form submission}} must trigger an email with well-formatted submission data

##Functional Review
[ ] Log in to the FOIA environment and go to the {{Webform}} page ({{/admin/structure/webform}})
[ ] Click *+ Add webform*
[ ] Create a form
[ ] Go to the content page ({{/admin/content}})
[ ] Edit any _Agency Component_
[ ] In the *Portal Submission Options* add your email address to the *Submission Email* field
[ ] At the bottom of the form find the *Request Submission Form* field and choose your new form
[ ] Go back to the {{Webform}} page ({{/admin/structure/webform}})
[ ] Find your form, fill it out and submit
[ ] Check your email to make sure that it contains the submission email and that the submission email contains "well formatted" text. The email should contain a section that says *The submission data is reproduced below in CSV format for your convenience.* with a comma separated string

##Developer Review
[/] Review [PR #63|https://github.com/usdoj/foia/pull/63]
[ ] Review [PR #65|https://github.com/usdoj/foia/pull/65]

###Setup
[/] Check out {{doj-94-tc}} locally
[/] Import config to add the new fields: {{drush cim}}

###Manual Testing
[/] Log in to the local environment and go to the {{Webform}} page ({{/admin/structure/webform}})
[/] Click *+ Add webform*
[/] Create a form
[/] Click the *Emails / Handlers* subtab
[/] Confirm that the *FOIA Email* handler is _enabled_
[/] Click the *View* tab
[/] Fill out the form and submit
[/] Go to the Watchdog log ({{/admin/reports/dblog}})
[/] You should see a message starting with *Unassociated form:*
[/] Go to the content page ({{/admin/content}})
[/] Edit an _Agency Component_
[/] At the bottom of the form find the *Request Submission Form* field and choose your new form
[/] Go back to the {{Webform}} page ({{/admin/structure/webform}})
[/] Find your form, fill it out and submit
[/] Go to the Watchdog log ({{/admin/reports/dblog}})
[/] If the _Agency Component_ has a *Submission Email* set, you should see a message reading *[Form name] webform sent FOIA email email.*
[/] If the *Submission Email* is not set, you will see a message starting with *No Submission Email:* with a link reading *Edit Component*
[/] Click the link and add the *Submission Email*
[/] Submit the form again and confirm via Watchdog that the email was sent.

###Automated Testing
[ ] Check out {{doj-94-dg}} locally
[ ] Import config {{drush cim}}
[ ] Install Maillog module {{composer install}}. You may also need to run {{composer update --lock}}
[ ] Enable Mailllog module {{drush @dojfoia.local en -y maillog}}
[ ] Run automated test {{blt tests:behat -D behat.paths=Request.feature}}
[ ] See {{1 scenario (1 passed) 53 steps (53 passed)}}

**Comment by malikkotob** [comment]
Merged into `develop`.
