### ISSUE TITLE
Do FOIA request emails to agencies need to be encrypted?

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#96]
We hadn't gotten a clear answer on this from our Security contact. We should schedule some time with the Privacy contact ASAP to get this answered.

**Comment by leahbannon** [comment]
Good news:

In an email from @malikkotob: "Acquia's database and filesystem are both encrypted, which means the data that will populate the contents of the e-mail will be encrypted at rest. When the e-mail is sent out, the third party e-mail service (potentially GovDelivery) would encrypt the e-mail during delivery (in transit). The agencies would then receive the e-mails in a decrypted state, and my understanding is that they would be responsible for encrypting the information thereafter. If that's the case, is there a need for Acquia to perform any further encryption?"

Response from CSS policy analyst: "From the description of the scenario, it sounds like Acquia would not be required to perform any additional encryption. As long as the data is encrypted at rest and in transit the OMB and DOJ requirements would be met."
