### ISSUE TITLE
Update authorization roles so that agency users can update any component within their agency

### ISSUE THREAD

**Issue by adborden** [18F/beta.foia.gov#97]
As an agency FOIA contact, in order to manage my agency's info in an efficient way based on existing processes, I need a user role that allows me to update any agency component's info in my agency.

The current expectation is that there is a single user per agency that manages all the agency info for all the agency components in the agency. This is based on [very rough preliminary research](https://github.com/18F/foia/issues/65#issuecomment-326058496) and seems like a reasonable place to start. We're only talking about edit permissions for now, no create/delete permissions yet.

## Acceptance criteria

- [x] New `Agency Manager` role created
- [x] New agency field on user to allow association of user to agency term
- [x] Users in the `Agency Manager` role can edit any agency component in the user's agency

**Comment by Tom-Camp** [comment]
## Developer Review

- [ ] Checkout [doj-97-tc](https://github.com/usdoj/foia/pull/67)
- [ ] Update config `drush cim`
- [ ] Clear the site cache `drush cr`
- [ ] Log in to and create a new user `/admin/people/create`
- [ ] Assign the new user the role of `Agency Manager`
- [ ] Associate the new user with the Agency Department of Energy via the `Agency` field
- [ ] Save the new user
- [ ] Either log out and log in with the new user or log in with the new user in a different browser
- [ ] Go to the DOE Agency Component _National Energy Technology Laboratory_ (`/node/2536`)
- [ ] You should see the `Edit` tab, but not the `Delete` tab
- [ ] Click `Edit` and edit the Agency Component.
- [ ] You should be able to edit the Agency Component.
- [ ] Try to delete the node by going to `/node/2536/delete`
- [ ] You should get an `Access Denied`
- [ ] Go to a non-DOE Agency Component, for example _AMTRAK (National Railroad Passenger Corporation)_ (`/node/3711`)
- [ ] You should not be able to edit or delete the Agency Component
- [ ] Go the _Department of Energy_ taxonomy term page (`/taxonomy/term/686`)
- [ ] You should see the `Edit` tab, but not the `Delete` tab
- [ ] Click `Edit` and edit the taxonomy term
- [ ] Try to delete the term by going to `/taxonomy/term/686/delete`
- [ ] You should get an `Access Denied`
- [ ] Try to edit or delete another taxonomy term, for example _AMTRAK_ (`/node/3711/edit`)
- [ ] You should get an `Access Denied`

**Comment by Tom-Camp** [comment]
## Functional Review

- [ ] Log in to and create a new user `/admin/people/create`
- [ ] Assign the new user the role of `Agency Manager`
- [ ] Associate the new user with the Agency Department of Energy via the `Agency` field
- [ ] Save the new user
- [ ] Either log out and log in with the new user or log in with the new user in a different browser
- [ ] Go to the DOE Agency Component _National Energy Technology Laboratory_ (`/node/2536`)
- [ ] You should see the `Edit` tab, but not the `Delete` tab
- [ ] Click `Edit` and edit the Agency Component.
- [ ] You should be able to edit the Agency Component.
- [ ] Try to delete the node by going to `/node/2536/delete`
- [ ] You should get an `Access Denied`
- [ ] Go to a non-DOE Agency Component, for example _AMTRAK (National Railroad Passenger Corporation)_ (`/node/3711`)
- [ ] You should not be able to edit or delete the Agency Component
- [ ] Go the _Department of Energy_ taxonomy term page (`/taxonomy/term/686`)
- [ ] You should see the `Edit` tab, but not the `Delete` tab
- [ ] Click `Edit` and edit the taxonomy term
- [ ] Try to delete the term by going to `/taxonomy/term/686/delete`
- [ ] You should get an `Access Denied`
- [ ] Try to edit or delete another taxonomy term, for example _AMTRAK_ (`/node/3711/edit`)
- [ ] You should get an `Access Denied`

**Comment by malikkotob** [comment]
Feedback in PR, moving out of Review/QA to have comments addressed.

**Comment by dangur** [comment]
# Developer Review
## National Energy Technology Laboratory is node/4656
## After saving `Agency Component`, I get the following message:
`Warning: array_intersect(): Argument #1 is not an array in _form_validation_foia_agency() (line 110 of modules/custom/foia_users/foia_users.module).
_form_validation_foia_agency(Array, Object)
call_user_func_array('_form_validation_foia_agency', Array) (Line: 83)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 270)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'node_agency_component_edit_form') (Line: 119)
Drupal\Core\Form\FormValidator->validateForm('node_agency_component_edit_form', Array, Object) (Line: 571)
Drupal\Core\Form\FormBuilder->processForm('node_agency_component_edit_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 38)
Drupal\jsonapi\StackMiddleware\FormatSetter->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 656)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`
## AMTRAK (National Railroad Passenger Corporation) is node/5831

**Comment by dangur** [comment]
php warning is no longer happening when Agency Manager saves Agency Component.

**Comment by dangur** [comment]
Added automated tests to branch `doj-97-dg`
### Developer Review
- [ ] Review [PR 72](https://github.com/usdoj/foia-api/pull/72)
- [ ] Checkout `doj-97-dg`
- [ ] Update config `drush cim`
- [ ] Clear Drupal caches `drush cr`
- [ ] Run automated tests `blt tests:behat -D behat.paths=Manager.feature`
- [ ] See that `6 scenarios (6 passed) 20 steps (20 passed)`

**Comment by barnyard777** [comment]
Mr. Gurin,

I am a FOIA Processor and would like to be part of the testing of the new FOIA portal as an agency user.  I work for Naval Air Technical Data and Engineering Service Center which is under Naval Air Systems Command.

Please advise.

V/R,

William Barnes
FOIA Specialist
619-545-3198

-----Original Message-----

**Comment by leahbannon** [comment]
Thanks @barnyard777! We'll add you to our list.

**Comment by malikkotob** [comment]
Merged into `develop`.

**Comment by barnyard777** [comment]
Leah,

Will I be provided with the URL when the testing starts?

V/R,

William Barnes
FOIA Specialist
619-545-3198

-----Original Message-----
